name: hostel_app
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  printing: ^5.12.0
  firebase_storage: ^12.1.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  connectivity_plus: ^6.0.3
  uuid: ^4.2.2
  image_picker: ^1.1.1
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.5
  file_picker: ^8.0.3
  flutter_pdfview: ^1.3.2
  intl: ^0.19.0
  firebase_core: ^3.4.0
  animations: ^2.0.11
  animate_do: ^3.3.4
  photo_view: ^0.15.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
