// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwXd9g9aiJxadX7zcLrzxdCR6rvY905Xk',
    appId: '1:161552808187:web:f9adb6fd0c8446580d185e',
    messagingSenderId: '161552808187',
    projectId: 'hostelapp-d2145',
    authDomain: 'hostelapp-d2145.firebaseapp.com',
    storageBucket: 'hostelapp-d2145.appspot.com',
    measurementId: 'G-1SZEP1NH27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4CvRktkdR0EnUf-qFykr_SoKp-u0IaDs',
    appId: '1:161552808187:android:2075075b3232bf360d185e',
    messagingSenderId: '161552808187',
    projectId: 'hostelapp-d2145',
    storageBucket: 'hostelapp-d2145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZGt1p-VyzVZQMnPFQ3F0kyN2stFwEQLE',
    appId: '1:161552808187:ios:6f8e5b6a0a394fe60d185e',
    messagingSenderId: '161552808187',
    projectId: 'hostelapp-d2145',
    storageBucket: 'hostelapp-d2145.appspot.com',
    iosBundleId: 'com.example.hostelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZGt1p-VyzVZQMnPFQ3F0kyN2stFwEQLE',
    appId: '1:161552808187:ios:6f8e5b6a0a394fe60d185e',
    messagingSenderId: '161552808187',
    projectId: 'hostelapp-d2145',
    storageBucket: 'hostelapp-d2145.appspot.com',
    iosBundleId: 'com.example.hostelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwXd9g9aiJxadX7zcLrzxdCR6rvY905Xk',
    appId: '1:161552808187:web:fc2dcf22eebfd3eb0d185e',
    messagingSenderId: '161552808187',
    projectId: 'hostelapp-d2145',
    authDomain: 'hostelapp-d2145.firebaseapp.com',
    storageBucket: 'hostelapp-d2145.appspot.com',
    measurementId: 'G-3LZTZ5LCSE',
  );
}
